### ISSUE TITLE
how to add?

### ISSUE THREAD

**Issue by rtng** [jonnieey/Sc-im-Tutorial#3]
hi,
this is actually no issue, but more an open question:
How to add this to sc-im?
Thank you a lot and kind regards

**Comment by rtng** [comment]
o.k. i opened your '.sc-files' with 'scim xyz.sc' and the rest explains by itself.
Very nice, thank you for that!
![Bildschirmfoto vom 2021-12-03 21-48-36](https://user-images.githubusercontent.com/67840237/144670963-4750ab82-f4a8-49cc-88d0-c1978e51077f.png)

**Comment by rtng** [comment]
o.k. i opened your '.sc-files' with 'scim xyz.sc' and the rest explains by itself.
Very nice, thank you for that!
![Bildschirmfoto vom 2021-12-03 21-48-36](https://user-images.githubusercontent.com/67840237/144670963-4750ab82-f4a8-49cc-88d0-c1978e51077f.png)

**Comment by jgarte** [comment]
Should we add a note to the README so that people might not be lost when they see these files and have to put two and two together like rtng had to do?

**Comment by jonnieey** [comment]
Yeah.
Could you maybe open a PR? It'd help alot.
Thanks.

**Comment by jonnieey** [comment]
Added brief description on usage.
