### ISSUE TITLE
Lesson 1 Navigation: `goc3` needs to be changed to `gtc3`.

### ISSUE THREAD

**Issue by deon-gracias** [jonnieey/Sc-im-Tutorial#5]
Sc-im now uses `gt` instead of `go`. This can be found in their [Quick Start](https://github.com/andmarti1424/sc-im#quick-start).

**Comment by jonnieey** [comment]
which version are you using? I'm using version 0.8.3 built from source, dev branch.
![2022-07-05-190602](https://user-images.githubusercontent.com/47189744/177370967-24b83ee2-5b23-4395-92a3-87ceb1266f4b.png)
![2022-07-05-190821](https://user-images.githubusercontent.com/47189744/177371352-9d2d97fe-3dd1-4617-b5dc-711d2683dea4.png)

**Comment by deon-gracias** [comment]
I'm using the main branch.
![Screenshot_2022-07-06-13-29-49_1920x1080](https://user-images.githubusercontent.com/58945356/177500462-0b002d23-1598-4ccf-a28b-de53de209ad0.png)

So sc-im, will eventually switch to `go` instead of `gt`. I guess it's ok to keep it as it is. 

I was just confused since currently the main branch had `gt`.
