### ISSUE TITLE
Running Lesson0 gives "syntax error"

### ISSUE THREAD

**Issue by halloleo** [jonnieey/Sc-im-Tutorial#7]
When I run 

    sc-im Lesson0_General.sc

I get an empty sheet and at the top the text (in red): `syntax error`

***

I have sc-im install via brew on macOS 10.15, done no customization and `sc-im --version` outputs:
```
SC-IM - version 0.8.2
-DNCURSES
-DMAXROWS 1048576
-DUNDO
-DXLS
-DXLSX
-DXLSX_EXPORT
-DXLUA
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="pbcopy <"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="pbpaste"
-DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD="scopen"
-DUSELOCALE
-DMOUSE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="sc-im"
-DHELP_PATH="/usr/local/Cellar/sc-im/0.8.2_4/share/sc-im"
-DLIBDIR="/usr/local/Cellar/sc-im/0.8.2_4/share/doc/sc-im"
-DDFLT_PAGER="less"
-DDFLT_EDITOR="vim"
-DCONFIG_DIR=".config/sc-im"
-DCONFIG_FILE="scimrc"
-DHISTORY_DIR=".cache"
-DHISTORY_FILE="sc-iminfo"
-DINS_HISTORY_FILE="sc-iminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP
Sc-im-Tutorial
```

**Comment by jonnieey** [comment]
I cant seem to reproduce the error. Do other sc files open with the error?

**Comment by halloleo** [comment]
Happens with other files in the tutorial as well.

But when I press `RET` twice I get to the sheet content as expected..

**Comment by jonnieey** [comment]
try running without your sc-im config file. or try to compile from source
using the dev branch of sc-im.

**Comment by halloleo** [comment]
I don't think I have any config file... 

sc-im seems to have created a empty directory ~/.config/sc-im though. Plus I found a cache file `/.cache/sc-iminfo` with some sc commands I had used in another file.

**Comment by halloleo** [comment]
It feels like as if sc-im does not start out in NORMAL mode.. But only with these sc files. If I start it _without_ a `.sc` file it works correct;y.

**Comment by jonnieey** [comment]
Maybe try some sc files from source code `sc-im/examples` or other sc
files. If there's still issues, open issue to sc-im repo. I'm able to
open the lessons without issue, sc-im compiled from source, dev branch

```
> ./sc-im --version
sc-im - version 0.8.3-main
-DNCURSES
-DMAXROWS 65536
-DUNDO
-DXLSX
-DXLUA
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="xclip -i -selection clipboard <"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="xclip -o -selection clipboard"
-DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD="scopen"
-DUSELOCALE
-DMOUSE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="sc-im"
-DHELP_PATH="/usr/local/share/sc-im"
-DLIBDIR="/usr/local/share/doc/sc-im"
-DDFLT_PAGER="less"
-DDFLT_EDITOR="vim"
-DCONFIG_DIR=".config/sc-im"
-DCONFIG_FILE="scimrc"
-DHISTORY_DIR=".cache"
-DHISTORY_FILE="sc-iminfo"
-DINS_HISTORY_FILE="sc-iminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP
```

**Comment by jonnieey** [comment]
Maybe try some sc files from source code `sc-im/examples` or other sc files.
If there's still issues, open issue to sc-im repo.
I'm able to open the lessons without issue, sc-im compiled from source, dev branch

```
> ./sc-im --version
sc-im - version 0.8.3-main
-DNCURSES
-DMAXROWS 65536
-DUNDO
-DXLSX
-DXLUA
-DDEFAULT_COPY_TO_CLIPBOARD_CMD="xclip -i -selection clipboard <"
-DDEFAULT_PASTE_FROM_CLIPBOARD_CMD="xclip -o -selection clipboard"
-DDEFAULT_OPEN_FILE_UNDER_CURSOR_CMD="scopen"
-DUSELOCALE
-DMOUSE
-DUSECOLORS
-D_XOPEN_SOURCE_EXTENDED
-D_GNU_SOURCE
-DSNAME="sc-im"
-DHELP_PATH="/usr/local/share/sc-im"
-DLIBDIR="/usr/local/share/doc/sc-im"
-DDFLT_PAGER="less"
-DDFLT_EDITOR="vim"
-DCONFIG_DIR=".config/sc-im"
-DCONFIG_FILE="scimrc"
-DHISTORY_DIR=".cache"
-DHISTORY_FILE="sc-iminfo"
-DINS_HISTORY_FILE="sc-iminfo"
-DHAVE_PTHREAD
-DAUTOBACKUP
```

**Comment by halloleo** [comment]
Good idea to try the sample files! Just did so. 

`wrap.sc` and `datetime.sc` work fine. **But `sheets/a.sc` shows the same behaviour**!

This is interesting, isn't it? I guess, i should file it as an issue with the sc-im repo.
